In [ ]:
pip install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting pandas
  Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 78.2 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.1 which is incompatible.
db-dtypes 1.5.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.1 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.1 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.1 which is incompatible.
Successfully installed pandas-3.0.1

# Пармезан

In [ ]:
import pandas as pd

file_path = '/content/ПАРМЕЗАН ПРОДАЖИ_отпр.xlsx'

df = pd.read_excel(file_path)

## Объем продаж

In [ ]:
monthly_sales = df.groupby('Месяц')['Вес'].sum().sort_values(ascending=False)
quarterly_sales = df.groupby('Квартал')['Вес'].sum().sort_values(ascending=False)
manager_sales = df.groupby('Менеджер')['Вес'].sum().sort_values(ascending=False)

monthly_df = monthly_sales.to_frame(name="Объем продаж").reset_index()
quarterly_df = quarterly_sales.to_frame(name="Объем продаж").reset_index()
manager_df = manager_sales.to_frame(name="Объем продаж").reset_index()

def hide_index(df):
    return df.style.set_properties(**{'text-align': 'left'}).hide(axis='index')

formatted_monthly_table = hide_index(monthly_df).set_caption("Таблица 1. Объем продаж по месяцам").format({"Объем продаж": "{:,.2f}"})
formatted_quarterly_table = hide_index(quarterly_df).set_caption("Таблица 2. Объем продаж по кварталам").format({"Объем продаж": "{:,.2f}"})
formatted_manager_table = hide_index(manager_df).set_caption("Таблица 3. Объем продаж по менеджерам").format({"Объем продаж": "{:,.2f}"})

display(formatted_monthly_table)
display(formatted_quarterly_table)
display(formatted_manager_table)

## Конверсия каналов сбыта

In [ ]:
total_sales = df["Вес"].sum()

channel_effectiveness = (
      df.groupby("Канал сбыта")["Вес"]
      .sum()
      .div(total_sales)
      .mul(100)
      .round(2)
      .sort_values(ascending=False)
)

print("Эффективность каналов сбыта (%):\n")
print(channel_effectiveness)

Эффективность каналов сбыта (%):

Канал сбыта
1.1 Дистрибьюторы              55.19
1.2.3 Фокусные клиенты         32.82
1.2.1 Региональные партнеры     4.55
1.2.2 МСК партнеры              3.97
1.3.1 Ключевой оптовик          2.06
1.7 Экспорт                     0.71
2.2 Региональные сети           0.70
Name: Вес, dtype: float64

## Эффективность менеджеров

In [ ]:
avg_sales_per_manager = df.groupby('Менеджер')['Вес'].mean().round(2)

sales_by_manager_df = avg_sales_per_manager.to_frame(name="Средний объем продаж").reset_index()

formatted_avg_sales_table = sales_by_manager_df.style \
    .hide(axis='index') \
    .set_caption("Таблица 5. Средний объем продаж по каждому менеджеру") \
    .format({"Средний объем продаж": "{:,.2f}"})

top_managers = avg_sales_per_manager.nlargest(5)

top_managers_df = top_managers.to_frame(name="Средний объем продаж").reset_index()

formatted_top_managers_table = top_managers_df.style \
    .hide(axis='index') \
    .set_caption("Таблица 6. Лидеры среди менеджеров") \
    .format({"Средний объем продаж": "{:,.2f}"})

display(formatted_avg_sales_table)
display(formatted_top_managers_table)

# Структура продаж

In [ ]:
import pandas as pd

file_path = '/content/МАССИВ_СТРУКТУРА ПРОДАЖ_отпр.xlsx'

df = pd.read_excel(file_path)

## Средняя цена по сегментам продукции

In [9]:
segment_mean_income = df.groupby('Сегмент.Код')['Цена за кг СНДС'].mean().round(2)

segment_mean_income_df = segment_mean_income.to_frame(name="Средняя цена за кг").reset_index()

formatted_segment_table = segment_mean_income_df.style\
    .hide(axis='index')\
    .set_caption("Таблица 1. Средний доход по сегментам продукции")\
    .format({"Средняя цена за кг": "{:,.2f}"})

display(formatted_segment_table)

## Определение наиболее продаваемых позиций по цене и популярности

In [ ]:
max_price_position = df.loc[df['Цена за кг СНДС'].idxmax()]

max_popularity_position = df.loc[df['Вес'].idxmax()]

price_leader_df = max_price_position[['Публичное наименование нормализованное', 'Цена за кг СНДС']].to_frame().T
popularity_leader_df = max_popularity_position[['Публичное наименование нормализованное', 'Вес']].to_frame().T

formatted_price_leader_table = price_leader_df.style\
    .hide(axis='index')\
    .set_caption("Таблица 2. Самая дорогая позиция")\
    .format({"Цена за кг СНДС": "{:,.2f}"})

formatted_popularity_leader_table = popularity_leader_df.style\
    .hide(axis='index')\
    .set_caption("Таблица 3. Самая популярная позиция")\
    .format({"Вес": "{:,.2f}"})

display(formatted_price_leader_table)
display(formatted_popularity_leader_table)

## Анализ изменений ценовых категорий и динамики их роста

In [10]:
month_price_change = df.groupby(['Сегмент.Код', 'Месяц'])['Цена за кг СНДС'].mean().unstack()

month_price_change.columns.name = None
month_price_change.index.name = 'Сегмент'

formatted_dynamics_table = month_price_change.style\
    .set_caption("Таблица 4. Динамика изменения цен по сегментам")\
    .format("{:,.2f}")

display(formatted_dynamics_table)

In [ ]:
product_sales = df.groupby('Публичное наименование нормализованное')['Вес'].sum().sort_values(ascending=False).head(5)
brand_sales = df.groupby('Марка (Бренд)')['Вес'].sum().sort_values(ascending=False).head(5)

best_products_df = product_sales.to_frame(name="Общий вес продаж").reset_index()
best_brands_df = brand_sales.to_frame(name="Общий вес продаж").reset_index()

formatted_best_products_table = best_products_df.style\
    .hide(axis='index')\
    .set_caption("Таблица 5. Самые продаваемые товары")\
    .format({"Общий вес продаж": "{:,.2f}"})

formatted_best_brands_table = best_brands_df.style\
    .hide(axis='index')\
    .set_caption("Таблица 6. Самые успешные бренды")\
    .format({"Общий вес продаж": "{:,.2f}"})

display(formatted_best_products_table)
display(formatted_best_brands_table)